### ISSUE TITLE
Main Course

### ISSUE THREAD

**Issue by ChrisFrendo** [ChrisFrendo/Recipes#5]
You should make sure that the main courses are in the main courses section of the book called recipe_book.txt in an organised fashion.

**Comment by xlokk73** [comment]
Make sure to organise and edit the book and add an introduction and conclusion.

**Comment by ChrisFrendo** [comment]
I'll add the introduction, can you handle the conclusion yourself? Thanks

**Comment by xlokk73** [comment]
Sure thing @ChrisFrendo.
